# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from os import system
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from prepare import predict_string
import sys, os

basedir = os.path.dirname(__file__)

def addToClipBoard(text):
    command = 'echo ' + text.strip() + '| clip'
    system(command)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(627, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.img_chooser = QtWidgets.QPushButton(self.centralwidget)
        self.img_chooser.setGeometry(QtCore.QRect(330, 60, 91, 23))
        self.img_chooser.setObjectName("img_chooser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 60, 150, 31))
        self.label_2.setObjectName("label_2")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 140, 291, 81))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(180, 240, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.copy = QtWidgets.QPushButton(self.centralwidget)
        self.copy.setGeometry(QtCore.QRect(400, 240, 61, 31))
        self.copy.setObjectName("copy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 627, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CAPTCHA SOLVER"))
        self.img_chooser.setText(_translate("MainWindow", "Chọn..."))
        self.img_chooser.clicked.connect(self.chooser_file_handle)
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Image(*.jpg):</span></p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"./0005.jpg\"/></p></body></html>"))
        self.copy.setText(_translate("MainWindow", "Copy"))
        self.copy.clicked.connect(self.copy_handle)

    def copy_handle(this):
        addToClipBoard(this.lineEdit.text())

    def chooser_file_handle(this):
        str = this.open_dialog()
        this.lineEdit.setText(str)

    def open_dialog(this): 
        selfilter = "JPEG (*.jpg)"
        file_name = QFileDialog.getOpenFileName(filter=selfilter)
        path = file_name[0]
        if not path == "":
            _translate = QtCore.QCoreApplication.translate
            src = "<html><head/><body><p><img src=\"{}\"/></p></body></html>".format(path)
            this.label_3.setText(_translate("MainWindow", src)) 
            return predict_string(path)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
